### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by sidd-03** [CS455-210241-211036/CS455_2048_game#1]
- [x] Create a webpage and set up the grid
- [x] Initialize the Game state
- [x] Implement tile logic  - Right Shift
- [x] Implement tile logic - Left Shift
- [x] Integrate the movements with keys
- [x] Generate new tile
- [x] Implement Score and Result Logic
- [x] Adding Colors to Tiles
- [x] Adding a reset button
